SELECT *
FROM customer
LIMIT 10

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender
LIMIT 10

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer)
LIMIT 10

--Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating::numeric), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-su
SELECT subscription_status, COUNT(customer_id) AS total_customers, SUM(purchase_amount) AS revenue, ROUND(AVG(purchase_amount), 2) AS avg_spend
FROM customer
GROUP BY subscription_status

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased, 
		ROUND((SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100) / COUNT(*), 2) AS per_of_purchases
FROM customer
GROUP BY item_purchased
ORDER BY per_of_purchases DESC
LIMIT 5

--Q7. Segment customers into New, Returning, and Loyal based on their 
--total number of previous purchases, and show the count of each segment.

WITH cust_seg AS(
	SELECT  customer_id, previous_purchases,
	CASE WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal' END AS customer_segment
	FROM customer
)

SELECT customer_segment, COUNT(*) AS tot_cust
FROM cust_seg
GROUP BY customer_segment
	

--Q8. What are the top 3 most purchased products within each category?
WITH ranked_items AS (
    SELECT
        category,
        item_purchased,
        COUNT(*) AS total_orders,
        DENSE_RANK() OVER (
            PARTITION BY category
            ORDER BY COUNT(*) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT
	category,
    item_purchased,
    total_orders,
	item_rank
FROM ranked_items
WHERE item_rank <= 3
ORDER BY category, item_rank;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
SELECT subscription_status, COUNT(*) AS no_of_customers
FROM customer
WHERE previous_purchases > 5
GROUP  BY subscription_status

--Q10. What is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group

